Candidate: CVE-2018-1000030
PublicDate: 2018-02-06
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-1000030
 https://bugs.python.org/file47157/0001-stop-crashes-when-iterating-over-a-file-on-multiple-.patch
 https://github.com/python/cpython/pull/3670
 https://github.com/python/cpython/pull/3672
 https://github.com/python/cpython/commit/6401e5671781eb217ee1afb4603cc0d1b0367ae6
 https://github.com/python/cpython/pull/5060
 https://bugs.python.org/msg309265
Description:
 [Heap-Buffer-Overflow and Heap-Use-After-Free in Objects/fileobject.c]
Ubuntu-Description:
Notes:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:

Patches_python2.7:
upstream_python2.7: needs-triage
precise/esm_python2.7: needs-triage
trusty_python2.7: needed
xenial_python2.7: needed
artful_python2.7: needed
devel_python2.7: needed

Patches_python2.6:
upstream_python2.6: needs-triage
precise/esm_python2.6: DNE
trusty_python2.6: DNE
xenial_python2.6: DNE
artful_python2.6: DNE
devel_python2.6: DNE

Patches_python3.6:
upstream_python3.6: needs-triage
precise/esm_python3.6: DNE
trusty_python3.6: DNE
xenial_python3.6: DNE
artful_python3.6: not-affected
devel_python3.6: not-affected

Patches_python3.7:
upstream_python3.7: needs-triage
precise/esm_python3.7: DNE
trusty_python3.7: DNE
xenial_python3.7: DNE
artful_python3.7: not-affected
devel_python3.7: not-affected

Patches_python3.4:
upstream_python3.4: needs-triage
precise/esm_python3.4: DNE
trusty_python3.4: not-affected
xenial_python3.4: DNE
artful_python3.4: DNE
devel_python3.4: DNE

Patches_python3.5:
upstream_python3.5: needs-triage
precise/esm_python3.5: DNE
trusty_python3.5: DNE
xenial_python3.5: not-affected
artful_python3.5: DNE
devel_python3.5: DNE

Patches_python3.2:
upstream_python3.2: needs-triage
precise/esm_python3.2: DNE
trusty_python3.2: DNE
xenial_python3.2: DNE
artful_python3.2: DNE
devel_python3.2: DNE
