Candidate: CVE-2010-1634
PublicDate: 2010-05-27
References:
 http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2010-1634
 http://svn.python.org/view?rev=81079&view=rev
 http://svn.python.org/view?rev=81045&view=rev
 http://bugs.python.org/issue8674
Description:
 Multiple integer overflows in audioop.c in the audioop module in Python
 2.6, 2.7, 3.1, and 3.2 allow context-dependent attackers to cause a denial
 of service (application crash) via a large fragment, as demonstrated by a
 call to audioop.lin2lin with a long string in the first argument, leading
 to a buffer overflow.  NOTE: this vulnerability exists because of an
 incorrect fix for CVE-2008-3143.5.
Ubuntu-Description:
Notes:
Bugs:
 http://bugs.python.org/issue8674
Priority: low
Discovered-by:
Assigned-to:

Patches_python2.4:
upstream_python2.4: needs-triage
dapper_python2.4: needed
hardy_python2.4: needed
jaunty_python2.4: needed
karmic_python2.4: needed
lucid_python2.4: DNE
devel_python2.4: DNE

Patches_python2.5:
upstream_python2.5: needs-triage
dapper_python2.5: DNE
hardy_python2.5: needed
jaunty_python2.5: needed
karmic_python2.5: needed
lucid_python2.5: DNE
devel_python2.5: DNE

Patches_python2.6:
 upstream: http://svn.python.org/view?view=rev&revision=81046
 upstream: http://svn.python.org/view?view=rev&revision=81080
upstream_python2.6: released (2.6.6-1)
dapper_python2.6: DNE
hardy_python2.6: DNE
jaunty_python2.6: needed
karmic_python2.6: needed
lucid_python2.6: needed
devel_python2.6: not-affected (2.6.6-5ubuntu1)

