Candidate: CVE-2019-14232
CRD: 2019-08-01 10:00:00 UTC
PublicDate: 2019-08-01 10:00:00 UTC
References: 
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14232
Description: 
 Denial-of-service possibility in django.utils.text.Truncator
Ubuntu-Description: 
Notes: 
Bugs: 
Priority: medium
Discovered-by:
Assigned-to: mdeslaur


Patches_python-django:
upstream_python-django: needs-triage
precise/esm_python-django: DNE
trusty_python-django: ignored (out of standard support)
trusty/esm_python-django: DNE
xenial_python-django: needed
bionic_python-django: needed
disco_python-django: needed
devel_python-django: needed
