Candidate: CVE-2018-1000807
PublicDate: 2018-10-08
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-1000807
 https://github.com/pyca/pyopenssl/pull/723
Description:
 Python Cryptographic Authority pyopenssl version prior to version 17.5.0
 contains a CWE-416: Use After Free vulnerability in X509 object handling
 that can result in Use after free can lead to possible denial of service or
 remote code execution.. This attack appear to be exploitable via Depends on
 the calling application and if it retains a reference to the memory.. This
 vulnerability appears to have been fixed in 17.5.0.
Ubuntu-Description:
Notes:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:


Patches_pyopenssl:
upstream_pyopenssl: released (17.5.0)
precise/esm_pyopenssl: needs-triage
trusty_pyopenssl: not-affected (code not present)
xenial_pyopenssl: needed
bionic_pyopenssl: not-affected (17.5.0-1)
devel_pyopenssl: not-affected (17.5.0-1)
