Candidate: CVE-2017-18207
PublicDate: 2018-03-01
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18207
 https://bugs.python.org/issue32056
Description:
 ** DISPUTED ** The Wave_read._read_fmt_chunk function in Lib/wave.py in
 Python through 3.6.4 does not ensure a nonzero channel value, which allows
 attackers to cause a denial of service (divide-by-zero and exception) via a
 crafted wav format audio file. NOTE: the vendor disputes this issue because
 Python applications "need to be prepared to handle a wide variety of
 exceptions."
Ubuntu-Description:
Notes:
Bugs:
Priority: low
Discovered-by:
Assigned-to: leosilva

Patches_python2.7:
upstream_python2.7: needs-triage
precise/esm_python2.7: needs-triage
trusty_python2.7: needs-triage
xenial_python2.7: needs-triage
artful_python2.7: needs-triage
devel_python2.7: needs-triage

Patches_python3.4:
upstream_python3.4: needs-triage
precise/esm_python3.4: DNE
trusty_python3.4: needs-triage
xenial_python3.4: DNE
artful_python3.4: DNE
devel_python3.4: DNE

Patches_python3.5:
upstream_python3.5: needs-triage
precise/esm_python3.5: DNE
trusty_python3.5: DNE
xenial_python3.5: needs-triage
artful_python3.5: DNE
devel_python3.5: DNE

Patches_python3.6:
upstream_python3.6: needs-triage
precise/esm_python3.6: DNE
trusty_python3.6: DNE
xenial_python3.6: DNE
artful_python3.6: needs-triage
devel_python3.6: needs-triage

Patches_python3.7:
upstream_python3.7: needs-triage
precise/esm_python3.7: DNE
trusty_python3.7: DNE
xenial_python3.7: DNE
artful_python3.7: needs-triage
devel_python3.7: needs-triage
