Candidate: CVE-2020-24583
CRD: 2020-09-01 10:00:00 UTC
PublicDate: 2020-09-01 10:00:00 UTC
References: 
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-24583
Description: 
 Incorrect permissions on intermediate-level directories on Python 3.7+
Ubuntu-Description: 
Notes: 
 mdeslaur> This issue is caused by a behavioural change in Python 3.7.
 mdeslaur> While python3.7 is available for bionic, it doesn't replace
 mdeslaur> python3.6, so bionic is not affected by this issue.
Mitigation: 
Bugs: 
Priority: medium
Discovered-by:
Assigned-to: mdeslaur
CVSS:


Patches_python-django:
upstream_python-django: pending (2.2.16)
precise/esm_python-django: DNE
trusty_python-django: ignored (out of standard support)
trusty/esm_python-django: not-affected (doesn't use python3.7)
xenial_python-django: not-affected (doesn't use python3.7)
bionic_python-django: not-affected (doesn't use python3.7)
focal_python-django: needed
devel_python-django: needed
