Running: /home/sarnold/bin/audit-code.sh -c python ./
Scanning './'
== subprocess_spawned() ==
./run_failure.py:6:    return os.system('bin/nosetests -s -d -v %s' % arg)
./kazoo/testing/common.py:144:        self.process = subprocess.Popen(

== memory_management() ==
(unsupported type 'python')

== files() ==
./setup.py:9:with open(os.path.join(here, 'README.rst')) as f:
./setup.py:11:with open(os.path.join(here, 'CHANGES.rst')) as f:
./kazoo/testing/common.py:107:        with open(config_path, "w") as config:
./kazoo/testing/common.py:122:            with open(config_path, "a") as config:
./kazoo/testing/common.py:130:        with open(os.path.join(data_path, "myid"), "w") as myid_file:
./kazoo/testing/common.py:133:        with open(log4j_path, "w") as log4j:
./kazoo/testing/common.py:210:        with open(os.path.join(self.working_path, "data", "myid"), "w") as fh:

== logging() ==
./kazoo/tests/test_connection.py:153:            raise struct.error()
./kazoo/tests/test_election.py:66:    def _check_thread_error(self):
./kazoo/tests/test_election.py:111:        self._check_thread_error()
./kazoo/tests/test_election.py:130:        self._check_thread_error()
./kazoo/tests/test_election.py:135:        self._check_thread_error()
./kazoo/client.py:230:                    warnings.warn('Passing retry configuration param %s to the'
./kazoo/client.py:374:            self.logger.debug("Skipping state change")
./kazoo/client.py:478:            warnings.warn("No chroot path exists, the chroot path "
./kazoo/client.py:1325:        self.client.logger.debug('Added %r to %r', request, self)
./kazoo/protocol/connection.py:108:            log.debug("Pinging server for r/w: %s:%s", host, port)
./kazoo/protocol/connection.py:244:                self.logger.info('Received error(xid=%s) %r', xid, callback_exception)
./kazoo/protocol/connection.py:261:            self.logger.debug('Read response %s', obj)
./kazoo/protocol/connection.py:313:            self.logger.warn('Received unknown event %r', watch.type)
./kazoo/protocol/connection.py:344:            self.logger.info('Received error(xid=%s) %r', xid, callback_exception)
./kazoo/protocol/connection.py:377:            self.logger.debug('Read close response')
./kazoo/protocol/connection.py:386:            self.logger.debug('Received Ping')
./kazoo/protocol/connection.py:389:            self.logger.debug('Received AUTH')
./kazoo/protocol/connection.py:401:            self.logger.debug('Reading for header %r', header)
./kazoo/protocol/connection.py:456:        self.logger.debug('ZK loop started')
./kazoo/protocol/connection.py:473:            self.logger.debug('Connection stopped')
./kazoo/protocol/connection.py:501:            self.logger.debug("Found r/w server to use, %s:%s", host, port)
./kazoo/protocol/connection.py:568:        self.logger.debug('    Using session_id: %r session_passwd: %s',
./kazoo/protocol/connection.py:597:        self.logger.debug('Session created, session_id: %r session_passwd: %s\n'
./kazoo/testing/common.py:37:def debug(sig, frame):
./kazoo/recipe/watchers.py:98:            warnings.warn('Passing additional arguments to DataWatch is'

== environment() ==

== privileged() ==
./kazoo/tests/test_client.py:72:    def test_chroot(self):
./kazoo/tests/test_client.py:931:    def test_unchroot(self):
./kazoo/tests/test_client.py:934:        self.assertEquals(client.unchroot('/a/b'), '/b')
./kazoo/tests/test_client.py:935:        self.assertEquals(client.unchroot('/b/c'), '/b/c')
./kazoo/client.py:606:    def unchroot(self, path):
./kazoo/client.py:763:                return self.unchroot(result.get())
./kazoo/protocol/serialization.py:345:    def unchroot(client, response):
./kazoo/protocol/serialization.py:349:                resp.append(client.unchroot(result))
./kazoo/protocol/connection.py:317:        path = client.unchroot(path)
./kazoo/protocol/connection.py:364:                    response = Transaction.unchroot(client, response)

== networking() ==
./kazoo/handlers/utils.py:33:    type_ = module.SOCK_STREAM
./kazoo/handlers/utils.py:34:    if hasattr(module, 'SOCK_CLOEXEC'):  # pragma: nocover
./kazoo/handlers/utils.py:36:        type_ |= module.SOCK_CLOEXEC
./kazoo/handlers/utils.py:37:    sock = module.socket(module.AF_INET, type_)
./setup.py:10:    README = f.read()
./setup.py:12:    CHANGES = f.read()
./kazoo/interfaces.py:54:    def socket(self):
./kazoo/tests/test_connection.py:44:        os.write(self.client._connection._write_pipe, b'\0')
./kazoo/tests/test_connection.py:238:        os.write(write_pipe, b'\0')
./kazoo/tests/test_connection.py:284:        def listen(state):
./kazoo/tests/test_barrier.py:59:        t1 = threading.Thread(target=make_barrier_one)
./kazoo/tests/test_barrier.py:61:        t2 = threading.Thread(target=make_barrier_two)
./kazoo/tests/test_barrier.py:109:        t1 = threading.Thread(target=make_barrier_one)
./kazoo/tests/test_barrier.py:111:        t2 = threading.Thread(target=make_barrier_two)
./kazoo/tests/test_threading_handler.py:102:        th = threading.Thread(target=wait_for_val)
./kazoo/tests/test_threading_handler.py:143:        th = threading.Thread(target=wait_for_val)
./kazoo/tests/test_threading_handler.py:169:        th = threading.Thread(target=wait_for_val)
./kazoo/tests/test_threading_handler.py:190:        th = threading.Thread(target=wait_for_val)
./kazoo/tests/test_threading_handler.py:212:        th = threading.Thread(target=wait_for_val)
./kazoo/tests/test_threading_handler.py:232:        th = threading.Thread(target=wait_for_val)
./kazoo/tests/test_election.py:36:        thread = threading.Thread(target=self._election_thread,
./kazoo/tests/test_election.py:42:    def _election_thread(self, contender_id, election):
./kazoo/tests/test_lock.py:47:        thread = threading.Thread(target=self._thread_lock_acquire_til_event,
./kazoo/tests/test_lock.py:81:            t = threading.Thread(target=self._thread_lock_acquire_til_event,
./kazoo/tests/test_lock.py:128:        thread = threading.Thread(target=self._thread_lock_acquire_til_event,
./kazoo/tests/test_lock.py:148:        thread1 = threading.Thread(target=self._thread_lock_acquire_til_event,
./kazoo/tests/test_lock.py:164:        thread1 = threading.Thread(target=self._thread_lock_acquire_til_event,
./kazoo/tests/test_lock.py:178:        thread2 = threading.Thread(target=self._thread_lock_acquire_til_event,
./kazoo/tests/test_lock.py:222:        def _thread(lock, event, timeout):
./kazoo/tests/test_lock.py:230:        t = threading.Thread(target=_thread, args=(lock1, e, timeout * 3))
./kazoo/tests/test_lock.py:283:        thread = threading.Thread(target=sema_one, args=())
./kazoo/tests/test_lock.py:334:        thread = threading.Thread(target=sema_one, args=())
./kazoo/tests/test_lock.py:358:        thread = threading.Thread(target=sema_one, args=())
./kazoo/tests/test_lock.py:395:        thread = threading.Thread(target=sema_one, args=())
./kazoo/tests/test_lock.py:408:        thread = threading.Thread(target=expire, args=())
./kazoo/tests/test_lock.py:463:        def _thread(sem, event, timeout):
./kazoo/tests/test_lock.py:471:        t = threading.Thread(target=_thread, args=(sem1, e, timeout * 3))
./kazoo/client.py:455:            os.write(write_pipe, b'\0')
./kazoo/client.py:525:        os.write(self._connection._write_pipe, b'\0')
./kazoo/protocol/connection.py:206:        b = self._read(4, timeout)
./kazoo/protocol/connection.py:208:        b = self._read(length, timeout)
./kazoo/protocol/connection.py:212:    def _read(self, length, timeout):
./kazoo/protocol/connection.py:248:        msg = self._read(4, timeout)
./kazoo/protocol/connection.py:250:        msg = self._read(length, timeout)
./kazoo/protocol/connection.py:277:        self._write(int_struct.pack(len(b)) + b, timeout)
./kazoo/protocol/connection.py:279:    def _write(self, msg, timeout):
./kazoo/protocol/connection.py:380:    def _read_socket(self, read_timeout):
./kazoo/protocol/connection.py:417:                os.read(self._read_pipe, 1)
./kazoo/protocol/connection.py:433:            os.read(self._read_pipe, 1)
./kazoo/protocol/connection.py:440:        os.read(self._read_pipe, 1)
./kazoo/protocol/connection.py:509:            read_timeout, connect_timeout = self._connect(host, port)
./kazoo/protocol/connection.py:528:                    response = self._read_socket(read_timeout)
./kazoo/protocol/connection.py:564:    def _connect(self, host, port):
./kazoo/testing/common.py:50:def listen():
./kazoo/testing/common.py:53:listen()
./kazoo/testing/common.py:108:            config.write("""
./kazoo/testing/common.py:123:                config.write("""
./kazoo/testing/common.py:131:            myid_file.write(str(self.server_info.server_id))
./kazoo/testing/common.py:134:            log4j.write("""
./kazoo/testing/common.py:211:            fh.write(str(self.server_info.server_id))
./kazoo/testing/common.py:267:        # required for a client to successfully connect (2s vs. 4s without
./kazoo/handlers/gevent.py:115:    def socket(self, *args, **kwargs):
./kazoo/handlers/gevent.py:116:        return create_tcp_socket(socket)
./kazoo/handlers/utils.py:30:def create_tcp_socket(module):
./kazoo/handlers/utils.py:37:    sock = module.socket(module.AF_INET, type_)
./kazoo/handlers/threading.py:201:        t = threading.Thread(target=thread_worker)
./kazoo/handlers/threading.py:247:    def socket(self):
./kazoo/handlers/threading.py:248:        return create_tcp_socket(socket)
./kazoo/handlers/threading.py:270:        t = threading.Thread(target=func, args=args, kwargs=kwargs)

== http:// ==
./kazoo/testing/common.py:20:#  along with txzookeeper.  If not, see <http://www.gnu.org/licenses/>.

== encryption ==
./setup.py:62:    url="https://kazoo.readthedocs.org",

== sql() ==

== tmp() ==

== priv_cmds (sudo, gksu, pkexec) ==

== envvars() ==

== webkit() ==

== comments (XXX, FIXME, TODO) ==
./kazoo/protocol/connection.py:395:                # XXX TODO: Should we fail out? Or handle auth failure

== unsafe input mechanisms ==
(unsupported type 'python')

